CREATE TABLE CORE_ACCOUNT(
SYSID BIGINT not null,
ACCOUNTID VARCHAR(20) not null,
USERID BIGINT,
PASSWORD VARCHAR(32),
FLAG NUMERIC(1),
RULE VARCHAR(4),
DATALIMIT NUMERIC(1),
SCENEID BIGINT,
ONLINE VARCHAR(2),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_ACCOUNT_ACCOUNTID UNIQUE (ACCOUNTID),
CONSTRAINT PK_CORE_ACCOUNT PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_ACCOUNT_FIRSTPAGE(
ACCOUNTID BIGINT,
MENUID BIGINT,
CONSTRAINT PK_CORE_ACCOUNT_FIRSTPAGE PRIMARY KEY (ACCOUNTID)
);

CREATE TABLE CORE_ACCOUNT_ORGANIZATION(
ACCOUNTID BIGINT,
ORGID BIGINT,
DEFAULTORG NUMERIC(1)
);

CREATE TABLE CORE_ACCOUNT_ROLE(
ACCOUNTID BIGINT,
ROLEID BIGINT
);

CREATE TABLE CORE_ACCOUNT_WORKGROUP(
ACCOUNTID BIGINT,
GROUPID BIGINT
);

CREATE TABLE CORE_APPLICATION(
SYSID BIGINT not null,
APPCODE VARCHAR(20) not null,
APPNAME VARCHAR(20) not null,
PROJECT VARCHAR(20),
REQADDRESS VARCHAR(50),
REMARK VARCHAR(400),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_APPLICATION_APPCODE UNIQUE (APPCODE),
CONSTRAINT PK_CORE_APPLICATION PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_MENU(
SYSID BIGINT not null,
PARENTID BIGINT,
APPID BIGINT,
MENUCODE VARCHAR(20) not null,
MENUNAME VARCHAR(100) not null,
ACTIONURI VARCHAR(80),
SORT NUMERIC,
ICON VARCHAR(100),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_MENU_MEUNCODE UNIQUE (MENUCODE),
CONSTRAINT PK_CORE_MENU PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_ORGANIZATION(
SYSID BIGINT not null,
PARENTID BIGINT,
ORGCODE VARCHAR(20) not null,
ORGNAME VARCHAR(100) not null,
LVL NUMERIC(1),
LFT NUMERIC(1),
RGT NUMERIC(1),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
GIS VARCHAR(2),
APPURL VARCHAR(100),
PREFLAG VARCHAR(1),
CONSTRAINT UK_GAP_ORGANIZATION_ORGCODE UNIQUE (ORGCODE),
CONSTRAINT PK_CORE_ORGANIZATION PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_PERSONNEL(
SYSID BIGINT not null,
ORGID BIGINT not null,
CODING VARCHAR(20) not null,
HISCODE VARCHAR(30),
NAME VARCHAR(20) not null,
SEX VARCHAR(1),
CARDID VARCHAR(20),
BIRTHDAY TIMESTAMP,
TELEPHONE VARCHAR(40),
EMAIL VARCHAR(40),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_CORE_PERSONNEL_CODING UNIQUE (CODING),
CONSTRAINT PK_CORE_PERSONNEL PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_PORTAL(
SYSID BIGINT not null,
PROTALCODE VARCHAR(20) not null,
PROTALNAME VARCHAR(20) not null,
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_PORTAL_PORTALCODE UNIQUE (PROTALCODE),
CONSTRAINT PK_CORE_PORTAL PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_PORTAL_FUNCTION(
PORTALID BIGINT,
FUNCID BIGINT
);

CREATE TABLE CORE_PROXY_PRIMARY(
TABLENAME VARCHAR(30),
SYSID BIGINT,
CONSTRAINT PK_CORE_PROXY_PRIMARY PRIMARY KEY (TABLENAME)
);

CREATE TABLE CORE_ROLE(
SYSID BIGINT not null,
ROLECODE VARCHAR(20) not null,
ROLENAME VARCHAR(20) not null,
RULE VARCHAR(4),
FLAG NUMERIC(1),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_ROLE_ROLECODE UNIQUE (ROLECODE),
CONSTRAINT Key_1 PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_ROLE_MENU(
ROLEID BIGINT,
MENUID BIGINT
);

CREATE TABLE CORE_ROLE_PORTAL(
ROLEID BIGINT,
PROTALID BIGINT
);

CREATE TABLE CORE_SCENE(
SYSID BIGINT not null,
SCENECODE VARCHAR(20) not null,
SCENENAME VARCHAR(20) not null,
MAINURL VARCHAR(80) not null,
DEFAULTFLAG NUMERIC(1),
CTS TIMESTAMP not null,
UTS TIMESTAMP not null,
CONSTRAINT UK_SCENE_SCENECODE UNIQUE (SCENECODE),
CONSTRAINT PK_CORE_SCENE PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_SHORTCUT(
ACCOUNTID BIGINT,
MENUID BIGINT,
CONSTRAINT UK_CORE_SHORTCUT_AID_MID UNIQUE (ACCOUNTID,MENUID)
);

CREATE TABLE CORE_WORKGROUP(
SYSID BIGINT not null,
GROUPNAME VARCHAR(40),
FLAG NUMERIC(1),
CTS TIMESTAMP,
UTS TIMESTAMP,
CONSTRAINT PK_CORE_WORKGROUP PRIMARY KEY (SYSID)
);

CREATE TABLE CORE_WORKGROUP_PERSONNEL(
GROUPID BIGINT,
PERSONNELID BIGINT
);

ALTER TABLE CORE_ACCOUNT_ORGANIZATION ADD CONSTRAINT FK_ACCOUNT_ORG_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES CORE_ACCOUNT(SYSID);
ALTER TABLE CORE_ACCOUNT_ORGANIZATION ADD CONSTRAINT FK_ACCOUNT_ORGANIZATION_ORGID FOREIGN KEY(ORGID) REFERENCES CORE_ORGANIZATION(SYSID);
ALTER TABLE CORE_ACCOUNT_ROLE ADD CONSTRAINT FK_ACCOUNT_ROLE_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES CORE_ACCOUNT(SYSID);
ALTER TABLE CORE_ACCOUNT_ROLE ADD CONSTRAINT FK_ACCOUNT_ROLE_ROLEID FOREIGN KEY(ROLEID) REFERENCES CORE_ROLE(SYSID);
ALTER TABLE CORE_ACCOUNT_WORKGROUP ADD CONSTRAINT FK_ACCOUNT_WORKGROUP_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES CORE_ACCOUNT(SYSID);
ALTER TABLE CORE_ACCOUNT_WORKGROUP ADD CONSTRAINT FK_ACCOUNT_WORKGROUP_GROUPID FOREIGN KEY(GROUPID) REFERENCES CORE_WORKGROUP(SYSID);
ALTER TABLE CORE_MENU ADD CONSTRAINT FK_MENU_APPID FOREIGN KEY(APPID) REFERENCES CORE_APPLICATION(SYSID);
ALTER TABLE CORE_PERSONNEL ADD CONSTRAINT FK_CORE_PERSONNEL_ORGID FOREIGN KEY(ORGID) REFERENCES CORE_ORGANIZATION(SYSID);
ALTER TABLE CORE_PORTAL_FUNCTION ADD CONSTRAINT FK_PORTAL_FUNCTION_PORTALID FOREIGN KEY(PORTALID) REFERENCES CORE_PORTAL(SYSID);
ALTER TABLE CORE_PORTAL_FUNCTION ADD CONSTRAINT FK_PORTAL_FUNCTION_FUNCID FOREIGN KEY(FUNCID) REFERENCES CORE_MENU(SYSID);
ALTER TABLE CORE_ROLE_MENU ADD CONSTRAINT FK_ROLE_MENU_ROLEID FOREIGN KEY(ROLEID) REFERENCES CORE_ROLE(SYSID);
ALTER TABLE CORE_ROLE_MENU ADD CONSTRAINT FK_ROLE_MENU_MENUID FOREIGN KEY(MENUID) REFERENCES CORE_MENU(SYSID);
ALTER TABLE CORE_ROLE_PORTAL ADD CONSTRAINT FK_ROLE_PROTAL_ROLEID FOREIGN KEY(ROLEID) REFERENCES CORE_ROLE(SYSID);
ALTER TABLE CORE_ROLE_PORTAL ADD CONSTRAINT FK_ROLE_PROTAL_PORTALID FOREIGN KEY(PROTALID) REFERENCES CORE_PORTAL(SYSID);
ALTER TABLE CORE_SHORTCUT ADD CONSTRAINT FK_CORE_SHORTCUT_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES CORE_ACCOUNT(SYSID);
ALTER TABLE CORE_SHORTCUT ADD CONSTRAINT FK_CORE_SHORTCUT_MENUID FOREIGN KEY(MENUID) REFERENCES CORE_MENU(SYSID);
ALTER TABLE CORE_WORKGROUP_PERSONNEL ADD CONSTRAINT FK_WORKGROUP_PERSONNEL_GROUPID FOREIGN KEY(GROUPID) REFERENCES CORE_WORKGROUP(SYSID);
ALTER TABLE CORE_WORKGROUP_PERSONNEL ADD CONSTRAINT FK_WORKGROUP_PERSONNEL_PERID FOREIGN KEY(PERSONNELID) REFERENCES CORE_PERSONNEL(SYSID);
