-- ger (颐乐养老康复中心） 审核权限数据
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(1,'外访申请单','GER_IBAB');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(2,'外访反馈表','GER_IBAC');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(3,'住养人员入院申请审批表','GER_IBAD');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(4,'出院申请（审批）通知单','GER_OAAA');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(5,'照护等级变更申请（审批）通知单','GER_NAAA');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(6,'床位变更申请（审批）通知单','GER_BAAA');
INSERT INTO core_bill_type(SYSID,NAME,FLAG) VALUES(7,'住养人员请假申请（审批）单','GER_HAAA');


INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(1,'养扶部签字权限',1,5,4,0,1);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(4,'部门负责人签字权限',1,5,4,0,2);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(7,'体检医生签字权限',1,5,4,0,3);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(8,'部门负责人签字权限',2,10,9,5,3);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(10,'﻿养服部部长签字权限',1,5,4,0,4);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(11,'收款处意见权限',2,10,9,5,4);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(13,'﻿变更生活区组长意见权限',1,5,4,0,5);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(14,'﻿养服部部长意见权限',2,10,9,5,5);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(15,'﻿财务经手人权限',3,15,14,10,5);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(16,'﻿变更生活区组长意见权限',1,5,4,0,6);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(17,'﻿养服部部长意见权限',2,10,9,5,6);
INSERT INTO CORE_AUDIT_OPT(SYSID,NAME,LVL,CPASS,NOTBY,PPASS,BILLID) VALUES(19,'﻿养服部意见权限',1,5,4,0,7);
