<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<title>服刑人员统计</title>
	<jsp:include page="../ltrhao-common.jsp"></jsp:include>
	<script type="text/javascript" src="${localCtx}/json/JzJzryJzlxxService.js"></script>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<style type="text/css">
		#sqjz_formJzryTjfx_all{
			/* 此处设置整体宽度
				若该宽度小于table宽度，则表会挤在一起
				若该宽度远远大于table宽度，则表右侧空白区域会增大
			 */
			width:2100px;
		}
		table{
			border-width: 1px;
			border-collapse:collapse;
			text-align:center;
			padding:10px;
		}
		table td{
			border-style: solid;
			border-width: 1px;
			font-size:15px;
		}
		table td div{
			margin:0 3px;
			
		}
		th{
			font-size:28px;
			text-align:center;
			margin:0 auto;
		}
		#sqjz_formJzryTjfx_all #first_row{
			width:100px;
		}
	</style>
</head>
<body>
	<div id="sqjz_formJzryTjfx_all">
		<table>
			<thead>
				<tr>
					<th colspan="53">社 区 服  刑 人 员 监 管</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td rowspan="6" id="first_row">地区\项目</td>
					<td rowspan="4"><div>在册<br>社区<br>矫正<br>人数</div></td>
					<td colspan="9">变动情况</td>
					<td rowspan="3" colspan="2">性别</td>
					<td rowspan="3" colspan="4">年龄</td>
					<td rowspan="3" colspan="4">户籍</td>
					<td rowspan="3" colspan="4">文化程度</td>
					<td rowspan="3" colspan="5">婚姻状况</td>
					<td rowspan="3" colspan="2">民族	</td>
					<td rowspan="3" colspan="3">就业就学	</td>
					<td rowspan="3" colspan="4">矫正期限</td>
					<td rowspan="3" colspan="5">矫正类别</td>
					<td rowspan="3" colspan="9">犯罪类型</td>
				</tr>
				<tr>
					<td rowspan="3"><div>本月<br>增加</div></td>
					<td colspan="8">本月减少</td>
				</tr>
				<tr>
					<td rowspan="2"><div>期满<br>解除</div></td>
					<td colspan="4">收监执行</td>
					<td colspan="2">死亡</td>
					<td rowspan="2">其他</td>
				</tr>
				<tr>
					<td><div>撤销<br>缓刑</div></td>
					<td><div>撤销<br>假释</div></td>
					<td><div>对暂予<br>监外执<br>行罪犯<br>决定收<br>监执行</div></td>
					<td><div>其他</div></td>
					<td><div>正常<br>死亡</div></td>
					<td><div>非正<br>常死<br>亡</div></td>
					<td><div>男性</div></td>
					<td><div>女性</div></td>
					<td><div>未满<br>十八<br>周岁</div></td>
					<td><div>十八<br>至四<br>十五<br>周岁</div></td>
					<td><div>四十<br>六至<br>六十<br>周岁</div></td>
					<td><div>六十<br>一周<br>岁以<br>上</div></td>
					<td><div>本省<br>户籍</div></td>
					<td><div>外省<br>户籍</div></td>
					<td><div>港澳<br>台籍</div></td>
					<td><div>外国<br>及无<br>国籍</div></td>
					<td><div>小学<br>及以<br>下</div></td>
					<td><div>初中</div></td>
					<td><div>高中</div></td>
					<td><div>大专<br>以上</div></td>
					<td><div>未婚</div></td>
					<td><div>已婚</div></td>
					<td><div>丧偶</div></td>
					<td><div>离异</div></td>
					<td><div>未知</div></td>
					<td><div>汉族</div></td>
					<td><div>少数<br>民族</div></td>
					<td><div>就学</div></td>
					<td><div>就业</div></td>
					<td><div>无业</div></td>
					<td><div>不满<br>一年</div></td>
					<td><div>一年<br>以上<br>不满<br>三年</div></td>
					<td><div>三年<br>以上<br>不满<br>五年</div></td>
					<td><div>五年<br>以上</div></td>
					<td><div>管制</div></td>
					<td><div>缓刑</div></td>
					<td><div>假释</div></td>
					<td><div>暂予<br>监外<br>执行</div></td>
					<td><div>剥夺<br>政治<br>权利</div></td>
					<td><div>危害<br>国家<br>安全</div></td>
					<td><div>危害<br>公共<br>安全</div></td>
					<td><div>破坏<br>经济<br>秩序</div></td>
					<td><div>侵犯<br>公民<br>人身<br>权利</div></td>
					<td><div>侵犯<br>财产</div></td>
					<td><div>妨害<br>社会<br>管理<br>秩序</td>
					<td><div>贪污<br>受贿</div></td>
					<td><div>渎职</div></td>
					<td><div>其他</div></td>
				</tr>
				<tr>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
					<td>人</td>
				</tr>
				<tr>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
				</tr>
				<tr>
					<td>呼和浩特市</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
				</tr>
				<tr>
					<td>包头市</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					
				</tr>
				<tr>
					<td>呼伦贝尔市</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					
				</tr>
				<tr>
					<td>兴安盟</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					
				</tr>
				<tr>
					<td>通辽市</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					
				</tr>
				<tr>
					<td>赤峰市</td>
					<td>1</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					
				</tr>
				<tr>
					<td>锡林郭勒盟</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>乌兰察布市</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>鄂尔多斯市</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>巴彦淖尔市</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>乌海市</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>阿拉善盟</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
				<tr>
					<td>合计</td>
					<td>2</td>
					<td>3</td>
					<td>4</td>
					<td>5</td>
					<td>6</td>
					<td>7</td>
					<td>8</td>
					<td>9</td>
					<td>10</td>
					<td>11</td>
					<td>12</td>
					<td>13</td>
					<td>14</td>
					<td>15</td>
					<td>16</td>
					<td>17</td>
					<td>18</td>
					<td>19</td>
					<td>20</td>
					<td>21</td>
					<td>22</td>
					<td>23</td>
					<td>24</td>
					<td>25</td>
					<td>26</td>
					<td>27</td>
					<td>28</td>
					<td>29</td>
					<td>30</td>
					<td>31</td>
					<td>32</td>
					<td>33</td>
					<td>34</td>
					<td>35</td>
					<td>36</td>
					<td>37</td>
					<td>38</td>
					<td>39</td>
					<td>40</td>
					<td>41</td>
					<td>42</td>
					<td>43</td>
					<td>44</td>
					<td>45</td>
					<td>46</td>
					<td>47</td>
					<td>48</td>
					<td>49</td>
					<td>50</td>
					<td>51</td>
					<td>52</td>
					<td>53</td>
				</tr>
			</tbody>
		</table>
	</div>
</body>
</html>